### ISSUE TITLE
Change of github ip addresses

### ISSUE THREAD

**Issue by heySourabh** [iitbyogastha/iitbyogastha.github.io#1]
Hi Vinay,

Please delete all the old "A records" from godaddy and add following host addresses for A records:

185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153

These are the new IP addresses of GitHub. Our site will stop working after some time, if this is not done.

You may do the following steps:
1) Login to godaddy
2) Manage DNS
3) Delete all 'A records', one-by-one
4) Add new 'A records' with above ip addresses, one-by-one

The new records must look something like:

![screenshot from 2019-01-17 08-13-09](https://user-images.githubusercontent.com/6834791/51292149-d6bce700-1a2f-11e9-8d43-c0ee674049e0.png)

Best Regards,
Sourabh

**Comment by vinaychourasiya** [comment]
Hi Sourabh

I have changed all previous "A record" and the new ones as you suggested.

This is snapshot of current DNS info. 
![screenshot from 2019-01-18 12-59-46](https://user-images.githubusercontent.com/36434775/51371787-26c7a680-1b21-11e9-8c6c-72234f6268a5.png)

Thanks
Vinay

**Comment by heySourabh** [comment]
Awesome! I am closing this issue.
